spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ilumina_db}
    username: ${DB_USERNAME:ilumina_user}
    password: ${DB_PASSWORD:ilumina_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: never

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: DEBUG